# -*- coding: utf-8 -*-
"""transform.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f5opfrT_N3E4uJMPepbHmvvlXeQUR8oZ
"""



import json
import re
import pandas as pd

def clear_number(text):
  """trích xuất số từ chuỗi"""
  if not text : return 0
  match = re.search(r"(\d+[,.]?\d*)", str(text).replace(",", "."))
  return float(match.group(1)) if match else 0

def parse_price_to_num(price_str):
    # 1. Kiểm tra nếu price_str không phải là chuỗi hoặc rỗng
    if not isinstance(price_str, str) or not price_str:
        return 0

    # 2. Lấy giá trị số (ví dụ: "6,9 tỷ" -> 6.9)
    val = clear_number(price_str)

    # 3. Chuyển chuỗi GỐC sang chữ thường để so sánh đơn vị
    price_lower = price_str.lower()

    # 4. Tính toán dựa trên đơn vị
    if "tỷ" in price_lower:
        return int(val * 1_000_000_000)
    elif "triệu" in price_lower:
        return int(val * 1_000_000)

    return int(val)

def split_address(address_str):
  """Tách địa chỉ thành Phường/Xã, Quận/Huyện, Tỉnh/Thành phố"""
  parts = [p.strip() for p in address_str.split(',')]
  # Batdongsan.com.vn thường để cấu trúc: [Số nhà/Tên đường], Phường, Quận, Tỉnh
  return {
      "city": parts[-1] if len(parts) > 0 else None,
      "district": parts[-2] if len(parts) > 1 else None,
      "ward": parts[-3] if len(parts) > 2 else None,
      "street": ", ".join(parts[:-3]) if len(parts) > 3 else None
  }

def preprocess_records(raw_data):

    processed_list = []

    for item in raw_data:
        specs = item.get('specs', {})

        # 1. Làm sạch thông số (Attributes)
        area = clear_number(specs.get('Diện tích', '0'))
        price_raw = specs.get('Khoảng giá', '0')

        # 2. Tính toán giá thực tế
        # Nếu giá là triệu/m2 thì nhân với diện tích để ra tổng giá cho DB
        final_price = parse_price_to_num(price_raw)
        if "triệu/m²" in price_raw:
            final_price = final_price * area

        # 3. Phân tách địa chỉ
        addr = split_address(item.get('short_address', ''))

        # 4. Cấu trúc lại bản ghi theo chuẩn Database
        refined = {
            "property_id_original": item.get('id'),
            "title": item.get('title'),
            "user_name": item.get('contact_name'),
            "user_phone": (item.get('contact_phone') or "").replace(" ***", ""),
            "price": final_price,
            "area": area,
            "address_full": item.get('short_address'),
            "province_name": addr['city'],
            "district_name": addr['district'],
            "ward_name": addr['ward'],
            "description": item.get('description'),
            "attr": {
                "bedrooms": int(clear_number(specs.get('Số phòng ngủ', 0))),
                "bathrooms": int(clear_number(specs.get('Số phòng tắm, vệ sinh', 0))),
                "floors": int(clear_number(specs.get('Số tầng', 0))),
                "direction": specs.get('Hướng nhà'),
                "legal": specs.get('Pháp lý'),
                "frontage": clear_number(specs.get('Mặt tiền', 0))
            },
            "images": item.get('images', []),
            "thumbnail": item.get('images')[0] if item.get('images') else None
        }
        processed_list.append(refined)

    return processed_list

df = pd.read_json('data/properties.json')
data_list = df.to_dict('records')

cleaned_data = preprocess_records(data_list)

df_cleaned = pd.DataFrame(cleaned_data)

df_cleaned.to_json('data/properties_cleaned.json',orient='records',force_ascii=False,indent=2)